### ISSUE TITLE
Second Loading Screen

### ISSUE THREAD

**Issue by reneil1337** [CryptoLibertus/CryptoFights_BUGS#2]
Screen freezes at second loading screen (after sound playback)

Browser: Chrome, 65.0.3325.181  64bit

![image](https://user-images.githubusercontent.com/29486630/38758710-971f5daa-3f72-11e8-829c-da4b40c475d3.png)
![image](https://user-images.githubusercontent.com/29486630/38758718-9f19af4c-3f72-11e8-8cfa-539394860552.png)
![image](https://user-images.githubusercontent.com/29486630/38758805-05c6c0ae-3f73-11e8-89d6-35efc35a25fc.png)

**Comment by CryptoLibertus** [comment]
This has been fixed. Thank you
