### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by bigdcrypto** [CryptoLibertus/CryptoFights_BUGS#6]
Still unable to get passed the second loading screen, it makes the sword sound effect and then doesn't go any furthur.

EDIT: I have tried using Chrome and FireFox and keep getting the same result.

**Comment by CryptoLibertus** [comment]
Can you try clearing your cache and trying again. I think you have the old files that are preventing the fixes to work.

**Comment by bigdcrypto** [comment]
Just tried clearing my cache and still getting stuck on the second loading screen.

**Comment by bigdcrypto** [comment]
![capture](https://user-images.githubusercontent.com/37839454/38773950-079a70ee-4020-11e8-8085-1915e606f105.JPG)

**Comment by CryptoLibertus** [comment]
Thank you, I will have our dev look into this. I want to make sure its not the old error and you have cleared your cache and hard reload the page.

**Comment by abeldantas** [comment]
@bigdcrypto can you send me the whole log please?
Also, can you try to run the game on a private window, just curious to see if it keeps happening.

**Comment by bigdcrypto** [comment]
Not the prettiest but this is the only way I could figure out how to save the entire log:
[beta.docx](https://github.com/CryptoLibertus/CryptoFights_BUGS/files/1915838/beta.docx)

Just tried using a private window(Chrome Incognito) and still no luck

I am currently using Windows 7 Enterprise at work and have also tried with Windows 10 at home

**Comment by abeldantas** [comment]
Thanks, I actually can now replicate your issue, should be fixed later
today.

**Comment by abeldantas** [comment]
Actually, could you give it a quick test again, I just deployed a new
version.

**Comment by bigdcrypto** [comment]
It is working now, great job!

**Comment by abeldantas** [comment]
thanks :)

**Comment by bigdcrypto** [comment]
You're welcome and thank you too! I'm excited to start testing/playing!
