### ISSUE TITLE
External links behaviour

### ISSUE THREAD

**Issue by WesLee91** [CryptoLibertus/CryptoFights_BUGS#7]
Windows 10
Google Chrome
Version 65.0.3325.181 (Official Build) (64-bit)

When clicking any link to another site a new tab is opened - however clicking the "More" button nothing happens (turns out my browser blocks popups and only displays a small icon that is easy to miss).

Probably best to have all links use the same "open in new tab" functionality, instead of using popups.

**Comment by abeldantas** [comment]
Yep, good catch.
Initially all links were popups, we had to figure out a way to trick the browser into opening new tabs without that warning, but we forgot about the more button. Fixing it now.

**Comment by CryptoLibertus** [comment]
this has been fixed.
